version: '3'
services:
  app:
    build:
      context: .
      dockerfile: app/Dockerfile.dev
    ports:
      - 5173:5173
    networks:
      - internal
    volumes:
      - ./app:/app/app
      - ./packages/file-graph:/app/packages/file-graph
  backend:
    build:
      context: .
      dockerfile: server/Dockerfile.dev
    networks:
      - internal
      - players
    ports:
      - '3000:3000'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./server/src:/app/server/src
      - ./server/swagger.yaml:/app/server/swagger.yaml
      - ./packages:/app/packages
      - ./quests:/app/quests
    environment:
      - MONGO_URL=mongodb://db:27017/odyssey-test
      - DOCKER_NETWORK=linux-odyssey-players
      - HOST_PWD=${PWD}
  db:
    image: mongo
    networks:
      - internal
    ports:
      - '27017:27017'
    volumes:
      - ./data:/data/db

  swagger:
    image: swaggerapi/swagger-editor:latest
    ports:
      - 8080:8080
    volumes:
      - ./server/swagger.yaml:/tmp/swagger.yaml
    environment:
      - SWAGGER_FILE=/tmp/swagger.yaml

  helloworld:
    image: lancatlin/linux-odyssey:helloworld
    build:
      context: .
      dockerfile: quests/helloworld/Dockerfile

  base:
    image: lancatlin/linux-odyssey:base
    build:
      context: .
      dockerfile: ./quests/Dockerfile

networks:
  internal:
  players:
    name: linux-odyssey-players
